# Generated by Django 3.0.8 on 2020-08-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='docfile',
            new_name='file',
        ),
    ]
